# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always


    ports: [ "53:53/tcp", "53:53/udp" ]
    extends:
      file: common.yml
      service: med-resources
    environment:
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
      ServerIP: 192.168.2.156 # This is the IP of the server running Pi-hole
      VIRTUAL_HOST: "pihole.local.racci.dev"
      WEBTHEME: "default-dark"
      WEBUIBOXEDLAYOUT: "traditional"

    networks:
      default:
        ipv4_address: 172.240.1.3
    volumes:
      - "/docker/pihole/pihole/:/etc/pihole/"
      - "/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/"
    labels:
      traefik.enable: true
      traefik.docker.network: "proxy"
      traefik.http.routers.pihole.entrypoints: "https"
      traefik.http.routers.pihole.rule: "Host(`pihole.local.racci.dev`)"
      traefik.http.routers.pihole.middlewares: "pihole-admin"
      traefik.http.routers.pihole.tls: true
      traefik.http.services.pihole.loadbalancer.server.port: "80"
      traefik.http.middlewares.pihole-admin.addprefix.prefix: "/admin"

networks:
  default:
    name: proxy
    external: true
