# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.9"

x-common: &base
  extends:
    file: common.yml
    service: low-resources

services:
  agent:
    <<: *base
    image: portainer/agent:latest
    expose: [ 9001 ]
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes
        read_only: true
        bind:
          create_host_path: false

  portainer:
    <<: *base
    image: portainer/portainer-ee:alpine
    security_opt: [ no-new-privileges=true ]
    depends_on: [ agent ]
    networks: [ default, proxy ]
    volumes:
      - type: bind
        source: /docker/portainer/data
        target: /data
    labels:
      traefik.enable: true
      traefik.docker.network: "proxy"
      traefik.http.routers.portainer.tls: true
      traefik.http.routers.portainer.entrypoints: "https"
      traefik.http.routers.portainer.middlewares: "portainer"
      traefik.http.routers.portainer.rule: "Host(`portainer.local.racci.dev`)"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"

networks:
  default:
    attachable: false
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

  proxy:
    name: proxy
    external: true
