# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.9"

configs:
  acme:
    file: /docker/traefik/acme.json
  traefik:
    file: /docker/traefik/traefik.yml
  traefik-conf:
    file: /docker/traefik/config.yml

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    security_opt: [ no-new-privileges:true ]
    ports: [ "80:80", "443:443" ]
    extends:
      file: common.yml
      service: low-resources
    networks:
      default:
        ipv4_address: 172.240.1.4
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    configs:
      - source: acme
        target: /config/acme.json
      - source: traefik
        target: /traefik.yml
      - source: traefik-conf
        target: /config/config.yml
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.racci.dev`)"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:password"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.local.racci.dev`)"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=local.racci.dev"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.racci.dev"
      - "traefik.http.routers.traefik-secure.tls.domains[1].main=local.elixirmc.co"
      - "traefik.http.routers.traefik-secure.tls.domains[1].sans=*.local.elixirmc.co"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  # TODO: Maybe make this not external?
  default:
    name: proxy
    external: true
